### PR TITLE
Fix for multiple foxes

### PR DESCRIPTION
**Pull request by inidona**
@Apollon77 here comes the fix for multiple oilfoxes with the new api, confirmend by @juettra

### CODE REVIEW

**Comment by inidona** [comment]
@GermanBluefox next time please use the right user in the changelog ;-)

**Comment by Apollon77** [comment]
I will fix the readme tomorow

**Comment by Apollon77** [comment]
done

**Comment by Apollon77** [comment]
Normally we always wait some days in latest but in this case I can update stable earlier

**Comment by Apollon77** [comment]
Stable update done

**Pull request merged**
